server:
  port: 8888
spring:
  datasource:
    name: product
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/sneaker?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
      username: root
      password: root
  servlet:
        multipart:
          max-file-size: 10Mb
          max-request-size: 100Mb
          enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zl.sneakerentity.model

redis:
  host: localhost
  port: 6379
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

#logging:
#  level:
#    com.zl.sneakerentity.dao: debug
