server:
  port: 8888
spring:
  datasource:
    name: product
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/sneaker?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zl.sneakerentity.model

redis:
  host: localhost
  port: 6379
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

upload:
  localtion:
    linux: /Users/le/Documents/image/
    mac: /Users/le/Documents/image/
    windows: D:/meatball/file/
  maxFileSize: 10240KB
  maxRequestSize: 102400KB